import { ImageResponse } from "next/og";

export const size = { width: 512, height: 512 };
export const contentType = "image/png";

// Dynamic app icon generated by Next.js — used for browser tab, PWA manifest, etc.
export default function Icon() {
    return new ImageResponse(
        (
            <div
                style={{
                    width: 512,
                    height: 512,
                    background: "linear-gradient(to bottom right, #0ea5e9, #2563eb)",
                    borderRadius: 112,
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                    justifyContent: "center",
                    gap: 0,
                }}
            >
                <div
                    style={{
                        fontSize: 200,
                        fontWeight: 900,
                        color: "white",
                        letterSpacing: -8,
                        lineHeight: 1,
                        fontFamily: "sans-serif",
                        textShadow: "0 4px 20px rgba(0,0,0,0.3)",
                    }}
                >
                    BC
                </div>
                <div
                    style={{
                        fontSize: 60,
                        fontWeight: 600,
                        color: "rgba(255,255,255,0.85)",
                        letterSpacing: 6,
                        fontFamily: "sans-serif",
                        marginTop: 4,
                    }}
                >
                    AI-Gram
                </div>
            </div>
        ),
        { ...size }
    );
}
